PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX budget:  <http://data.europa.eu/budget#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?g ?pays ?name ?year ?cat ?percent
WHERE{
	{?pays a dbo:country;
		foaf:name ?name;
		dbo:budget ?b1.
	
	?b1 dbo:budgetYear "2015";
		dbo:category "Defense";
		budget:percent ?percent.}
	UNION
	{GRAPH ?g { 
		?pays a dbo:country;
			foaf:name ?name;
			dbo:budget ?b2.
		
		?b2 dbo:budgetYear "2015";
   			dbo:category ?cat;
    		budget:percent ?percent.}
	}
	
	FILTER (?percent != -1).
}